<?php

namespace AppBundle\Repository;

/**
 * JuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuegoRepository extends \Doctrine\ORM\EntityRepository
{
}
